# Generated by Django 5.2 on 2025-05-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0006_stripecredentials_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('direct_api', 'Direct API Integration'), ('workflow', 'Workflow Automation Platform')], default='direct_api', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, help_text='Base URL for the API endpoint', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for workflow platforms', null=True)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('token', 'Token Authentication'), ('basic', 'Basic Authentication')], default='none', max_length=20)),
                ('auth_data', models.JSONField(blank=True, default=dict, help_text='Authentication credentials')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration.platformintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(help_text='Field name from your system', max_length=255)),
                ('target_field', models.CharField(help_text='Field name expected by the platform', max_length=255)),
                ('parent_path', models.CharField(blank=True, help_text='Dot-separated path for nested fields (e.g., customer.address)', max_length=255, null=True)),
                ('field_type', models.CharField(choices=[('string', 'Text'), ('number', 'Number'), ('boolean', 'True/False'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('array', 'Array/List'), ('object', 'Object')], default='string', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order within the parent object')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integration.platformintegration')),
            ],
            options={
                'ordering': ['parent_path', 'order'],
            },
        ),
    ]
