# Generated by Django 5.2 on 2025-10-21 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Business name used for website generation', max_length=255)),
                ('ai_prompt', models.TextField(help_text="User's custom prompt for AI website generation")),
                ('html_file_path', models.CharField(help_text='Path to the generated HTML file in media directory', max_length=500)),
                ('is_published', models.BooleanField(default=True, help_text='Whether the website is publicly accessible')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times the website has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the website was first generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the website was last regenerated')),
                ('user', models.OneToOneField(help_text='User who owns this website', on_delete=django.db.models.deletion.CASCADE, related_name='generated_website', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Website',
                'verbose_name_plural': 'Generated Websites',
                'ordering': ['-created_at'],
            },
        ),
    ]
