# Generated by Django 5.2 on 2025-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='business_slug',
            field=models.SlugField(default='kashif-mehmood', help_text='URL-friendly slug generated from business name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
