# Generated by Django 5.2 on 2025-10-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_website', '0002_generatedwebsite_business_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteGenerationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(help_text="User's prompt/request for this generation")),
                ('ai_response', models.TextField(blank=True, help_text="AI's response or status message", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the generation', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Generation progress (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used in this generation')),
                ('generation_time_seconds', models.FloatField(default=0.0, help_text='Time taken to generate (in seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this session was completed', null=True)),
                ('website', models.ForeignKey(help_text='The website this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='generation_sessions', to='ai_website.generatedwebsite')),
            ],
            options={
                'verbose_name': 'Website Generation Session',
                'verbose_name_plural': 'Website Generation Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
