# Generated by Django 5.2 on 2025-06-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_path', models.CharField(max_length=255)),
                ('entry_point', models.CharField(default='main.py', max_length=100)),
                ('manifest', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PluginPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='plugins.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'permission_name')},
            },
        ),
        migrations.CreateModel(
            name='PluginSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_type', models.CharField(max_length=20)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='plugins.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'setting_name')},
            },
        ),
    ]
