# Generated by Django 5.2 on 2025-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='plugin_class',
            field=models.CharField(blank=True, help_text='Name of the plugin class to instantiate', max_length=100, null=True),
        ),
    ]
