# Generated by Django 5.2 on 2025-10-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_plugin_plugin_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plugins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plugin',
            name='code_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of plugin code for integrity verification', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('disabled', 'Disabled')], default='pending', help_text='Current status of the plugin', max_length=20),
        ),
        migrations.AddField(
            model_name='plugin',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_plugins', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plugin',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Whether the plugin is enabled (can only be true if approved)'),
        ),
    ]
