# Generated by Django 5.2 on 2025-10-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_plugin_approved_at_plugin_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('import_error', 'Import Error'), ('runtime_error', 'Runtime Error'), ('permission_error', 'Permission Error'), ('timeout_error', 'Timeout Error'), ('dependency_error', 'Dependency Error')], max_length=50)),
                ('hook_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='plugins.plugin')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_plugin_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('version_spec', models.CharField(max_length=50)),
                ('installed_version', models.CharField(blank=True, max_length=20, null=True)),
                ('install_status', models.CharField(choices=[('pending', 'Pending'), ('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('install_error', models.TextField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='plugins.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='PluginExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_name', models.CharField(max_length=100)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='plugins.plugin')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['plugin', 'hook_name', '-executed_at'], name='plugins_plu_plugin__b025d5_idx')],
            },
        ),
    ]
