# Generated by Django 5.2 on 2025-10-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_alter_pluginsetting_options_pluginsetting_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PluginSetting',
        ),
    ]
