# Generated by Django 5.2 on 2025-04-29 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='business.industry')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('initial_response_delay', models.PositiveIntegerField(default=5, help_text='Delay in minutes before first contact')),
                ('follow_up_attempts', models.PositiveIntegerField(default=3)),
                ('follow_up_interval', models.PositiveIntegerField(default=60, help_text='Interval in minutes between follow-ups')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('icon', models.CharField(default='concierge-bell', help_text='FontAwesome icon name', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Color code for the service icon', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='business.business')),
            ],
            options={
                'verbose_name': 'Service Offering',
                'verbose_name_plural': 'Service Offerings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, help_text='Amount saved compared to buying services individually', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='business.business')),
                ('services', models.ManyToManyField(related_name='packages', to='business.serviceoffering')),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('boolean', 'Yes/No'), ('email', 'Email'), ('phone', 'Phone Number'), ('url', 'URL'), ('textarea', 'Text Area')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='business.business')),
            ],
            options={
                'verbose_name': 'Business Custom Field',
                'verbose_name_plural': 'Business Custom Fields',
                'ordering': ['display_order', 'name'],
                'unique_together': {('business', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='IndustryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('boolean', 'Yes/No'), ('email', 'Email'), ('phone', 'Phone Number'), ('url', 'URL'), ('textarea', 'Text Area')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='business.industry')),
            ],
            options={
                'verbose_name': 'Industry Field',
                'verbose_name_plural': 'Industry Fields',
                'ordering': ['display_order', 'name'],
                'unique_together': {('industry', 'slug')},
            },
        ),
    ]
