# Generated by Django 5.2 on 2025-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffering',
            name='identifier',
            field=models.SlugField(blank=True, help_text='Unique identifier for this service (e.g., number_of_bedrooms)', max_length=120),
        ),
        migrations.DeleteModel(
            name='ServicePackage',
        ),
    ]
