# Generated by Django 5.2 on 2025-10-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_serviceitem_field_options_serviceitem_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service_offering',
            field=models.ForeignKey(blank=True, help_text='Link this item to a specific service offering', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='business.serviceoffering'),
        ),
    ]
