# Generated by Django 5.2 on 2025-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_serviceitem_service_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='fixed', max_length=20),
        ),
    ]
