# Generated by Django 5.2 on 2025-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_serviceitem_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='option_pricing',
            field=models.JSONField(blank=True, help_text="Pricing configuration for field options (Yes/No, Select). Format: {'option_name': {'price_type': 'paid/free', 'price_value': 0.00}}", null=True),
        ),
    ]
