# Generated by Django 5.2 on 2025-10-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_serviceitem_option_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfiguration',
            name='ai_model_preference',
            field=models.CharField(choices=[('openai', 'OpenAI GPT-4o'), ('gemini', 'Google Gemini 2.5 Pro')], default='openai', help_text='Preferred AI model for website generation', max_length=20),
        ),
    ]
