# Generated by Django 5.2 on 2025-05-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_remove_businessconfiguration_follow_up_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetellAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('retell_agent_id', models.CharField(max_length=100)),
                ('retell_phone_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'verbose_name': 'Retell Agent',
                'verbose_name_plural': 'Retell Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
