# Generated by Django 5.2 on 2025-07-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_serviceitem_field_options_serviceitem_field_type'),
        ('retell_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retellagent',
            options={},
        ),
        migrations.RemoveField(
            model_name='retellagent',
            name='retell_agent_id',
        ),
        migrations.RemoveField(
            model_name='retellagent',
            name='retell_phone_number',
        ),
        migrations.AddField(
            model_name='retellagent',
            name='agent_id',
            field=models.CharField(default='12', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retellagent',
            name='agent_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retellagent',
            name='voice_id',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retellagent',
            name='agent_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='retellagent',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retell_agents', to='business.business'),
        ),
        migrations.CreateModel(
            name='RetellLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_id', models.CharField(max_length=255, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('general_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retell_llms', to='business.business')),
            ],
        ),
        migrations.AddField(
            model_name='retellagent',
            name='llm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='retell_agent.retellllm'),
        ),
    ]
