"""
Django settings for services_ai project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Plugins directory
PLUGINS_DIR = os.path.join(BASE_DIR, 'plugins')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-1234567890')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv('DJANGO_DEBUG') == 'True' else False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    
    'django_eventstream',  # For SSE notifications
    # Custom apps
    'ai_agent.apps.AiAgentConfig',
    'bookings.apps.BookingsConfig',
    'invoices.apps.InvoicesConfig',
    'leads.apps.LeadsConfig',
    'retell_agent.apps.RetellAgentConfig',
    'core.apps.CoreConfig',
    'business.apps.BusinessConfig',
    'accounts.apps.AccountsConfig',
    'integration.apps.IntegrationConfig',
    'dashboard.apps.DashboardConfig',
    'notifications.apps.NotificationsConfig',
    'plugins.apps.PluginsConfig',
    'licence.apps.LicenceConfig',
    'analytics.apps.AnalyticsConfig',
    'staff.apps.StaffConfig',
    'customer.apps.CustomerConfig',
    'ai_website.apps.AiWebsiteConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'licence.middleware.LicenceMiddleware',
    'staff.middleware.StaffAccessMiddleware',
]

ROOT_URLCONF = 'services_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'licence.context_processors.licence_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'services_ai.wsgi.application'
ASGI_APPLICATION = "services_ai.asgi.application"

import dj_database_url

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG == True:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv('DATABASE_URL')),
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# STRIPE
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')

BASE_URL = 'http://127.0.0.1:8000'

# OPENAI
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# GEMINI
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://servicesai.up.railway.app',
]

# Allow iframes from same origin for template preview
X_FRAME_OPTIONS = 'SAMEORIGIN'

Q_CLUSTER = {
    'name': 'services_ai',
    'workers': 8,
    'recycle': 500,
    'timeout': 300,
    'retry': 3600,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 4,
    'label': 'Django Q2',
    'orm': 'default',
    'max_attempts': 3,
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

LICENCE_AMOUNT = os.getenv('LICENCE_AMOUNT', 99.99)



RETELL_BASE_URL = os.getenv('RETELL_BASE_URL')
RETELL_API_KEY = os.getenv('RETELL_API_KEY')


# Django EventStream Configuration
EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.DjangoModelStorage'



EMAILIT_API_KEY = os.getenv('EMAILIT_API_KEY')