# Generated by Django 5.2 on 2025-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingeventtype_alter_bookingevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingeventtype',
            name='configuration',
            field=models.JSONField(default=dict, help_text='Event configuration including fields, settings, etc.'),
        ),
    ]
