# Generated by Django 5.2 on 2025-10-07 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingeventtype_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingevent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='field_values',
            field=models.JSONField(blank=True, default=dict, help_text='Stores dynamic field values from event type custom fields'),
        ),
    ]
