# Generated by Django 5.2 on 2025-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingevent_created_by_bookingevent_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingeventtype',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of user groups/roles that can access this event. Empty = all users'),
        ),
    ]
